"""
inference_asbury.py — Auto-regressive flood-depth inference for the Asbury Park domain.

Adapted from inference.py (Barbados training domain). Differences:
  - Static features live in Asbury_Park/DEM/ on a 936×1080 EPSG:26918 grid
    (30 m cells, matching the training domain's pixel dimensions and
    resolution). dem.tif is already in metres; --dem_unit ft converts
    legacy feet DEMs on load.
  - Rainfall forcing comes from MRMS hourly QPE GeoTIFFs (lat/lon, ~1 km cells)
    named YYYYMMDD-HHMMSS.tif in US Eastern local time; each is reprojected
    onto the model grid at load time.
  - No ground truth exists for this domain, so there is no --eval; the GIF
    shows Rainfall | Prediction panels (over satellite imagery if available).
  - The initial condition is generated by rolling the model through a short
    spin-up under small uniform rainfall (--spinup_steps/--spinup_rain;
    --spinup_steps 0 gives a zero-depth cold start), and after every rollout
    step depths below 1 mm are zeroed to stop accumulation error.
  - All units are metric: the DEM (dem.tif, from the 10 m bathy-gap-filled
    grid) and every output depth (GeoTIFF bands, max-depth raster, colorbars)
    are in METRES; the model itself runs in its native normalised-mm units.

Usage
-----
python inference_asbury.py \
    --ckpt_path  logs/tfno_.../checkpoints/best.ckpt \
    --model_type fno \
    --gif

# restrict to a sub-window of the downloaded rain series (Eastern local time)
python inference_asbury.py \
    --ckpt_path  logs/tfno_.../checkpoints/best.ckpt \
    --model_type fno \
    --start_time 2026-07-06T00:00 --end_time 2026-07-07T00:00
"""

import argparse
from datetime import datetime, timedelta
from pathlib import Path

import imageio
import matplotlib
matplotlib.use('Agg')
import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
import numpy as np
import rasterio
from rasterio.warp import reproject, Resampling
import torch
from tqdm import tqdm

from data_loader import NORM_DEM, NORM_MAN, NORM_SLOPE, NORM_RAIN, NORM_DEPTH, _read
from inference import _set_deterministic, _hann2d, patched_forward, load_model

FT_TO_M = 0.3048

_DEFAULT_STATIC_DIR = Path('/home/hl1138/surrogate/Asbury_Park/DEM')
_DEFAULT_RAIN_DIR   = Path('/home/hl1138/surrogate/Asbury_Park/rainfall')
_DEM_NAME           = 'NJDEM_150ft_AsburyPark_512.tif'

# Depths below this (m) are filtered out of all depth visualisations
# (0.1 m = common "actionable depth" convention in urban flood mapping)
_WET_THRESHOLD = 0.1

# Depths below this (m, = 1 mm) are zeroed after every rollout step so numerical
# residue can't accumulate over long auto-regressive runs
_MIN_DEPTH_M = 0.001

# Colourful hazard ramp for depth: bright blue → cyan → green → yellow → red
# (turbo with its muddy dark-navy start trimmed so shallow water stays vivid)
_FLOOD_CMAP = mcolors.LinearSegmentedColormap.from_list(
    'flood', plt.get_cmap('turbo')(np.linspace(0.12, 1.0, 256)))

# MRMS clips carry a GRIB pseudo-CRS (sometimes dropped on write); their
# coordinates are plain lon/lat, so treat them as WGS84.
_RAIN_FALLBACK_CRS = 'EPSG:4326'


# --------------------------------------------------------------------------- #
# Static / dynamic data loaders
# --------------------------------------------------------------------------- #

def load_static(static_dir: Path, dem_unit: str = 'm'):
    """Return (static (4,H,W), land_mask (1,H,W), grid profile dict)."""
    dem_path = static_dir / 'dem.tif'
    if not dem_path.exists():
        dem_path = static_dir / _DEM_NAME

    with rasterio.open(dem_path) as src:
        grid = {'crs': src.crs, 'transform': src.transform,
                'width': src.width, 'height': src.height,
                'profile': src.profile.copy()}

    dem = _read(dem_path)
    if dem_unit == 'ft':
        dem *= FT_TO_M                                   # training DEM is metres
    dem      = dem / NORM_DEM
    manning  = _read(static_dir / 'manning_coef.tif')  / NORM_MAN
    pervious = _read(static_dir / 'pervious_cover.tif')
    slope    = _read(static_dir / 'slope.tif')         / NORM_SLOPE
    static   = torch.from_numpy(np.stack([dem, manning, pervious, slope], axis=0))

    mask = torch.from_numpy(_read(static_dir / 'land_mask.tif')[None].astype(np.float32))
    return static, mask, grid


def load_satellite(sat_path: Path, grid: dict) -> np.ndarray | None:
    """Return an (H, W, 3) float RGB array in [0,1] on the model grid, or None."""
    if sat_path is None or not sat_path.exists():
        return None
    with rasterio.open(sat_path) as src:
        H, W = grid['height'], grid['width']
        if (src.width, src.height) == (W, H) and src.transform == grid['transform']:
            rgb = src.read()
        else:
            rgb = np.zeros((3, H, W), dtype=np.uint8)
            for i in range(3):
                reproject(src.read(i + 1), rgb[i],
                          src_transform=src.transform, src_crs=src.crs,
                          dst_transform=grid['transform'], dst_crs=grid['crs'],
                          resampling=Resampling.average)
    return np.moveaxis(rgb, 0, -1).astype(np.float32) / 255.0


# gamma < 1 spreads colour resolution over shallow/mid depths instead of letting
# a few extreme pixels compress everything into the pale end (range unchanged)
_DEPTH_GAMMA = 0.4


def _overlay_depth(ax, depth_np, satellite, land, vmax, zoom=None):
    """Draw depth on ax — over the satellite RGB if given, else standalone."""
    masked = depth_np.copy()
    norm = mcolors.PowerNorm(gamma=_DEPTH_GAMMA, vmin=0, vmax=max(vmax, 1e-6))
    if zoom is not None:
        r0, r1, c0, c1 = zoom
        masked = masked[r0:r1, c0:c1]
        land = land[r0:r1, c0:c1]
        satellite = satellite[r0:r1, c0:c1] if satellite is not None else None
    if satellite is not None:
        ax.imshow(satellite, origin='upper', aspect='equal', interpolation='nearest')
        wet = (masked >= _WET_THRESHOLD) & land
        masked[~wet] = np.nan                        # dry/ocean → see-through
        # opacity follows the same nonlinear ramp as the colours
        alpha = np.zeros_like(masked)
        alpha[wet] = 0.35 + 0.5 * np.clip(masked[wet] / max(vmax, 1e-6), 0, 1) ** _DEPTH_GAMMA
        return ax.imshow(masked, cmap=_FLOOD_CMAP, norm=norm, alpha=alpha,
                         origin='upper', aspect='equal', interpolation='nearest')
    masked[(masked < _WET_THRESHOLD) | ~land] = np.nan
    return ax.imshow(masked, cmap=_FLOOD_CMAP, norm=norm,
                     origin='upper', aspect='equal', interpolation='nearest')


def load_rain_sequence(
    rain_dir:   Path,
    grid:       dict,
    start_time: datetime | None = None,
    end_time:   datetime | None = None,
):
    """
    Load MRMS hourly rain tifs, reproject each onto the model grid.

    Returns (times, rain_seq): parallel lists of datetimes and normalised
    (1, H, W) tensors.
    """
    entries = []
    for f in sorted(rain_dir.glob('*.tif')):
        try:
            t = datetime.strptime(f.stem, '%Y%m%d-%H%M%S')
        except ValueError:
            continue
        if start_time is not None and t < start_time:
            continue
        if end_time is not None and t > end_time:
            continue
        entries.append((t, f))

    if len(entries) < 2:
        raise FileNotFoundError(
            f'Need at least 2 hourly rain files in {rain_dir} within the '
            f'requested window, found {len(entries)}')

    gaps = [b[0] for a, b in zip(entries, entries[1:])
            if b[0] - a[0] != timedelta(hours=1)]
    if gaps:
        print(f'[load_rain_sequence] WARNING: {len(gaps)} gap(s) in the hourly '
              f'series, first at {gaps[0]}')

    H, W = grid['height'], grid['width']
    times, seq = [], []
    for t, f in tqdm(entries, desc='Reprojecting rain', unit='file'):
        with rasterio.open(f) as src:
            rain = src.read(1).astype(np.float32)
            rain = np.maximum(rain, 0.0)                 # MRMS missing flags < 0
            dst  = np.zeros((H, W), dtype=np.float32)
            reproject(
                rain, dst,
                src_transform=src.transform,
                src_crs=src.crs or _RAIN_FALLBACK_CRS,
                dst_transform=grid['transform'], dst_crs=grid['crs'],
                resampling=Resampling.bilinear,
            )
        times.append(t)
        seq.append(torch.from_numpy(dst[None] / NORM_RAIN))
    return times, seq


# --------------------------------------------------------------------------- #
# Full auto-regressive rollout (no GT exists for this domain)
# --------------------------------------------------------------------------- #

def _zero_small_depth(depth_norm: torch.Tensor) -> torch.Tensor:
    """Zero depths below _MIN_DEPTH_M (input is normalised depth, mm/NORM_DEPTH)."""
    thr = _MIN_DEPTH_M * 1000.0 / NORM_DEPTH
    return torch.where(depth_norm < thr, torch.zeros_like(depth_norm), depth_norm)


def spin_up(
    model:      torch.nn.Module,
    static:     torch.Tensor,       # (4, H, W)
    steps:      int,
    rain_mmhr:  float,
    patch_size: int,
    stride:     int,
    device:     torch.device,
) -> tuple[torch.Tensor, torch.Tensor]:
    """
    Generate an initial depth state by rolling the model under a small uniform
    rainfall for `steps` hours, starting from zero depth.

    Returns (depth (1,H,W) normalised, last rain field (1,H,W) normalised) to
    seed the real rollout.
    """
    hann      = _hann2d(patch_size)
    H, W      = static.shape[1:]
    rain      = torch.full((1, H, W), rain_mmhr / NORM_RAIN)
    depth_t   = torch.zeros_like(rain)
    rain_prev = torch.zeros_like(rain)

    for _ in tqdm(range(steps), desc=f'Spin-up ({rain_mmhr} mm/hr)', unit='step'):
        x_full  = torch.cat([static, rain_prev, rain, depth_t], dim=0)
        depth_t = _zero_small_depth(patched_forward(
            model, x_full, patch_size, stride, device, hann))
        rain_prev = rain

    d_m = depth_t * NORM_DEPTH / 1000.0
    print(f'[spin_up] initial condition after {steps} h: '
          f'max {d_m.max().item():.3f} m, mean {d_m.mean().item():.4f} m, '
          f'wet(>{_MIN_DEPTH_M} m) {100 * (d_m > _MIN_DEPTH_M).float().mean().item():.1f}%')
    return depth_t, rain


def run_inference(
    model:      torch.nn.Module,
    static:     torch.Tensor,       # (4, H, W)
    rain_seq:   list[torch.Tensor],
    patch_size: int,
    stride:     int,
    device:     torch.device,
    init_depth: torch.Tensor | None = None,   # (1,H,W) normalised
    init_rain:  torch.Tensor | None = None,   # (1,H,W) normalised
) -> list[torch.Tensor]:
    """
    Roll out depth auto-regressively from init_depth (zero if None).

    After every step, depths below _MIN_DEPTH_M are zeroed so tiny numerical
    residue cannot accumulate over long rollouts.

    preds[i] is the depth (metres, (1,H,W)) after the rain hour rain_seq[i],
    i.e. at time times[i] + 1 h.
    """
    hann      = _hann2d(patch_size)
    depth_t   = init_depth if init_depth is not None else torch.zeros_like(rain_seq[0])
    rain_prev = init_rain  if init_rain  is not None else torch.zeros_like(rain_seq[0])

    predictions = []
    for t in tqdm(range(len(rain_seq)), desc='Rolling out', unit='step'):
        rain_t = rain_seq[t]
        x_full = torch.cat([static, rain_prev, rain_t, depth_t], dim=0)  # (7,H,W)
        depth_next = _zero_small_depth(patched_forward(
            model, x_full, patch_size, stride, device, hann
        ))                                                               # (1,H,W) norm
        predictions.append(depth_next * NORM_DEPTH / 1000.0)            # → m
        rain_prev = rain_t
        depth_t   = depth_next

    return predictions


# --------------------------------------------------------------------------- #
# Outputs
# --------------------------------------------------------------------------- #

def save_geotiff(preds, times, grid, out_path: Path) -> None:
    """Save predicted depth sequence as a multi-band GeoTIFF (metres, float32)."""
    profile = grid['profile'].copy()
    profile.update(count=len(preds), dtype='float32', nodata=-9999.0)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with rasterio.open(out_path, 'w', **profile) as dst:
        for i, (pred, t) in enumerate(zip(preds, times)):
            band = pred.squeeze(0).numpy().clip(0, 30.0).astype(np.float32)
            dst.write(band, i + 1)
            label = (t + timedelta(hours=1)).strftime('%Y-%m-%d %H:%M')
            dst.update_tags(i + 1, description=f'pred depth (m) at {label} local')

    print(f'Saved {len(preds)}-band GeoTIFF → {out_path}')


def save_max_depth(preds, land_mask, grid, out_stem: Path,
                   satellite: np.ndarray | None = None, zoom=None) -> None:
    """Per-pixel temporal max depth: GeoTIFF + PNG (over satellite if given)."""
    max_depth = torch.stack(preds, dim=0).max(dim=0).values   # (1, H, W)
    arr = max_depth.squeeze(0).numpy().astype(np.float32)
    land = land_mask.squeeze(0).numpy() > 0

    profile = grid['profile'].copy()
    profile.update(count=1, dtype='float32', nodata=-9999.0)
    tif_path = out_stem.with_name(out_stem.name + '_max_depth.tif')
    with rasterio.open(tif_path, 'w', **profile) as dst:
        dst.write(np.where(land, arr, -9999.0), 1)
        dst.update_tags(1, description='temporal max water depth (m)')
    print(f'Saved max-depth GeoTIFF → {tif_path}')

    vmax = max(float(arr[land].max()), 1e-3)
    fig, ax = plt.subplots(figsize=(7, 7))
    fig.patch.set_facecolor('#1a1a2e')
    im = _overlay_depth(ax, arr, satellite, land, vmax, zoom=zoom)
    ax.set_title('Pred max depth', color='white', fontsize=13, pad=6)
    ax.axis('off')
    cb = plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cb.set_label('m', color='white', fontsize=10)
    cb.ax.yaxis.set_tick_params(color='white', labelcolor='white')
    cb.outline.set_edgecolor('white')
    png_path = out_stem.with_name(out_stem.name + '_max_depth.png')
    fig.savefig(str(png_path), dpi=150, bbox_inches='tight',
                facecolor=fig.get_facecolor())
    plt.close(fig)
    print(f'Saved max-depth plot → {png_path}')


def save_gif(
    preds, times, rain_seq, land_mask, gif_path: Path,
    fps: int = 2, max_depth: float | None = None, max_rain: float | None = None,
    satellite: np.ndarray | None = None, zoom=None,
) -> None:
    """Two-panel animated GIF: Rainfall | Prediction over satellite imagery."""
    land = land_mask.squeeze(0).numpy() > 0

    if max_depth is None:
        max_depth = max(float(p.squeeze(0).numpy()[land].max()) for p in preds)
        max_depth = max(max_depth, 1e-3)
    if max_rain is None:
        max_rain = max(float(r.max().item()) * NORM_RAIN for r in rain_seq)
        max_rain = max(max_rain, 1.0)

    gif_path.parent.mkdir(parents=True, exist_ok=True)
    frames = []
    for pred, rain, t in tqdm(zip(preds, rain_seq, times),
                              total=len(preds), desc='Rendering GIF', unit='frame'):
        p_np = pred.squeeze(0).numpy()
        r_np = rain.squeeze(0).numpy() * NORM_RAIN
        if zoom is not None:
            r0, r1, c0, c1 = zoom
            r_np = r_np[r0:r1, c0:c1]

        fig, axes = plt.subplots(1, 2, figsize=(11, 5))
        fig.patch.set_facecolor('#1a1a2e')

        im = axes[0].imshow(r_np, cmap='YlGnBu',
                            norm=mcolors.PowerNorm(gamma=_DEPTH_GAMMA, vmin=0,
                                                   vmax=max(max_rain, 1e-6)),
                            origin='upper', aspect='equal', interpolation='nearest')
        axes[0].set_title('Rainfall', color='white', fontsize=12, pad=6)
        ims = [(im, 'mm/hr')]

        im = _overlay_depth(axes[1], p_np, satellite, land, max_depth, zoom=zoom)
        axes[1].set_title('Prediction', color='white', fontsize=12, pad=6)
        ims.append((im, 'm'))

        for ax, (im, unit) in zip(axes, ims):
            ax.axis('off')
            cb = plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
            cb.set_label(unit, color='white', fontsize=9)
            cb.ax.yaxis.set_tick_params(color='white', labelcolor='white')
            cb.outline.set_edgecolor('white')
        fig.suptitle(f"{t.strftime('%Y-%m-%d %H:%M')} local",
                     color='white', fontsize=13, y=1.01)
        fig.tight_layout()

        fig.canvas.draw()
        buf = np.frombuffer(fig.canvas.buffer_rgba(), dtype=np.uint8)
        w, h = fig.canvas.get_width_height()
        frames.append(buf.reshape(h, w, 4)[..., :3])
        plt.close(fig)

    imageio.mimsave(str(gif_path), frames, fps=fps, loop=0)
    print(f'Saved {len(frames)}-frame GIF → {gif_path}')


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

def parse_args():
    p = argparse.ArgumentParser(
        description='Auto-regressive flood depth inference for Asbury Park')

    p.add_argument('--ckpt_path',  required=True, help='Lightning checkpoint (.ckpt)')
    p.add_argument('--static_dir', default=str(_DEFAULT_STATIC_DIR),
                   help='Static-feature directory (DEM, manning_coef.tif, …)')
    p.add_argument('--rain_dir',   default=str(_DEFAULT_RAIN_DIR),
                   help='Directory of hourly MRMS tifs named YYYYMMDD-HHMMSS.tif')
    p.add_argument('--start_time', default=None,
                   help='First rain hour to use, ISO format, Eastern local time '
                        '(default: first available file)')
    p.add_argument('--end_time',   default=None,
                   help='Last rain hour to use, inclusive (default: last file)')
    p.add_argument('--dem_unit',   default='m', choices=['ft', 'm'],
                   help='Unit of the DEM file; ft is converted to metres '
                        '(default m — dem.tif from the 10 m bathy DEM is metres; '
                        'pass ft when using the legacy NJDEM_150ft file)')
    p.add_argument('--satellite',  default='auto',
                   help='RGB GeoTIFF drawn under the depth overlay in plots/GIF '
                        '(reprojected to the model grid if needed). "auto" looks '
                        'in <static_dir>/../satellite/; "none" disables')
    p.add_argument('--out_dir',    default=None,
                   help='Output directory (default: predictions/asbury_<exp_name>)')
    p.add_argument('--model_type', default='fno', choices=['fno', 'cnn', 'gnn', 'gno'])
    p.add_argument('--spinup_steps', type=int, default=6,
                   help='Hours of small uniform rainfall the model is rolled '
                        'through to generate the initial depth state (0 = cold start)')
    p.add_argument('--spinup_rain', type=float, default=1.0,
                   help='Uniform spin-up rainfall intensity in mm/hr (default 1.0)')
    p.add_argument('--patch_size', type=int, default=512)
    p.add_argument('--stride',     type=int, default=256,
                   help='Patch stride; must be < patch_size to avoid coverage gaps')
    p.add_argument('--gif',        action='store_true',
                   help='Save rainfall/prediction animation')
    p.add_argument('--zoom_shp',   default=None,
                   help='Shapefile/GeoJSON whose bounds crop the GIF and '
                        'max-depth plot display (outputs GeoTIFFs are unaffected)')
    p.add_argument('--fps',        type=int, default=2)
    p.add_argument('--max_depth',  type=float, default=None,
                   help='Depth colour-scale cap in metres (default: auto)')
    p.add_argument('--max_rain',   type=float, default=None,
                   help='Rainfall colour-scale cap in mm/hr (default: auto)')
    p.add_argument('--device',     default='cuda' if torch.cuda.is_available() else 'cpu')
    p.add_argument('--seed',       type=int, default=42)

    # Model hyperparameter fallbacks for old checkpoints without model_cfg
    p.add_argument('--in_channels',    type=int,   default=7)
    p.add_argument('--hidden_dim',     type=int,   default=64)
    p.add_argument('--n_layers',       type=int,   default=4)
    p.add_argument('--modes1',         type=int,   default=16)
    p.add_argument('--modes2',         type=int,   default=16)
    p.add_argument('--rank',           type=float, default=0.42)
    p.add_argument('--domain_padding', type=float, default=0.1)
    p.add_argument('--base_channels',  type=int,   default=64)
    p.add_argument('--depth',          type=int,   default=4)
    p.add_argument('--num_heads',      type=int,   default=4)
    p.add_argument('--num_phys',       type=int,   default=8)
    p.add_argument('--global_ratio',   type=float, default=0.1)
    p.add_argument('--global_k',       type=int,   default=8)

    return p.parse_args()


def main():
    args = parse_args()
    _set_deterministic(args.seed)
    device = torch.device(args.device)

    start_time = datetime.fromisoformat(args.start_time) if args.start_time else None
    end_time   = datetime.fromisoformat(args.end_time)   if args.end_time   else None

    static, land_mask, grid = load_static(Path(args.static_dir), args.dem_unit)
    times, rain_seq = load_rain_sequence(
        Path(args.rain_dir), grid, start_time, end_time)

    satellite = None
    if args.satellite.lower() != 'none':
        if args.satellite.lower() == 'auto':
            # resolve next to the static features so it works on any mirror
            sat_dir = Path(args.static_dir).resolve().parent / 'satellite'
            cands = (sorted(sat_dir.glob('*_grid.tif'))
                     or sorted(sat_dir.glob('*_512.tif'))
                     or sorted(sat_dir.glob('*.tif')))
            sat_path = cands[0] if cands else sat_dir / '(none found)'
        else:
            sat_path = Path(args.satellite)
        satellite = load_satellite(sat_path, grid)
        if satellite is None:
            print(f'[main] WARNING: satellite image {sat_path} not found — '
                  f'plotting without basemap')
        else:
            print(f'Basemap  : {sat_path}')

    stem = (f'asbury_{args.model_type}'
            f'_{times[0].strftime("%Y%m%d%H")}_{times[-1].strftime("%Y%m%d%H")}')
    if args.out_dir is not None:
        out_dir = Path(args.out_dir)
    else:
        exp_name = Path(args.ckpt_path).parent.parent.parent.name
        out_dir  = Path('predictions') / f'asbury_{exp_name}'

    print(f'Model    : {args.model_type}  |  checkpoint: {args.ckpt_path}')
    print(f'Rain     : {times[0]} → {times[-1]}  ({len(times)} hourly steps, local time)')
    print(f'Device   : {device}')
    print(f'Out dir  : {out_dir}')

    model = load_model(Path(args.ckpt_path), args.model_type, args).to(device)

    init_depth = init_rain = None
    if args.spinup_steps > 0:
        init_depth, init_rain = spin_up(
            model, static, args.spinup_steps, args.spinup_rain,
            args.patch_size, args.stride, device)
        # keep the generated initial condition inspectable
        ic_path = out_dir / f'{stem}_init_depth.tif'
        profile = grid['profile'].copy()
        profile.update(count=1, dtype='float32', nodata=None)
        ic_path.parent.mkdir(parents=True, exist_ok=True)
        with rasterio.open(ic_path, 'w', **profile) as dst:
            dst.write((init_depth * NORM_DEPTH / 1000.0).squeeze(0).numpy(), 1)
            dst.update_tags(1, description=(
                f'initial depth (m): {args.spinup_steps} h spin-up '
                f'at {args.spinup_rain} mm/hr uniform rain'))
        print(f'Saved initial condition → {ic_path}')

    zoom = None
    if args.zoom_shp:
        import geopandas as gpd
        zb = gpd.read_file(args.zoom_shp).to_crs(grid['crs']).total_bounds
        r0, c0 = rasterio.transform.rowcol(grid['transform'], zb[0], zb[3])
        r1, c1 = rasterio.transform.rowcol(grid['transform'], zb[2], zb[1])
        zoom = (max(0, r0), min(grid['height'], r1),
                max(0, c0), min(grid['width'], c1))
        print(f'Zoom     : {args.zoom_shp} -> rows {zoom[0]}:{zoom[1]}, cols {zoom[2]}:{zoom[3]}')

    preds = run_inference(
        model      = model,
        static     = static,
        rain_seq   = rain_seq,
        patch_size = args.patch_size,
        stride     = args.stride,
        device     = device,
        init_depth = init_depth,
        init_rain  = init_rain,
    )
    print(f'Predicted {len(preds)} steps')

    save_geotiff(preds, times, grid, out_dir / f'{stem}.tif')
    save_max_depth(preds, land_mask, grid, out_dir / stem, satellite=satellite,
                   zoom=zoom)
    if args.gif:
        save_gif(preds, times, rain_seq, land_mask, out_dir / f'{stem}.gif',
                 fps=args.fps, max_depth=args.max_depth, max_rain=args.max_rain,
                 satellite=satellite, zoom=zoom)


if __name__ == '__main__':
    main()
